```mermaid
classDiagram
    User --> Reservation : makes
    Reservation --> Room : reserves
    Reservation --> API : uses
    Reservation --> Verification : requires
    Room --> Verification : linked to

    class User{
        +String Name
        +int PhoneNumber
        +String EmailAddress
        +LogIn()
        +CheckIn()
        +bookTheRoom()
    }
    class Reservation{
        +String bookingID
        +String roomName
        +int roomNumber
        +int numberofGuest
        +String status
        +String paymentStatus
        +checkInReservation()
        +cancelReservation()
        +updateStatus()
        +validateCheckIn()
        +printReceipt()
    }
    class Room{
        +String roomID
        +String roomType
        +int guestNumber
        +String availabilityStatus
        +double price
        +String bookingID
        +bookRoom()
        +updateAvailabilityStatus()
        +getRoomDetails()
    }
    class API{
        +String url
        -String token
        +fetchRoomData()
        +fetchReservationData()
    }
    class Verification{
        -String userID
        +Image passportPhoto
        +Image selfiePhoto
        +String verificationStatus
        +uploadPassport()
        +uploadSelfiePhoto()
        +updateVerificationStatus()
    }
```
